stages:
  - test
  - deploy

test:
  image: java:8
  services:
    - postgres:latest
  variables:
    POSTGRES_DB: othellocrown_account_test
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: ""
  before_script:
    - chmod +x gradlew
    - cp src/main/resources/application-test.properties.example src/main/resources/application-test.properties
  script:
    - ./gradlew checkstyleMain
    - ./gradlew test
    - ./gradlew jacocoTestReport
    - cat build/reports/jacoco/test/html/index.html
  only:
    - merge_requests
    - master

deploy:
  stage: deploy
  image: ruby:2.3
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - wget -qO- https://cli-assets.heroku.com/install-ubuntu.sh | sh
    - cp src/main/resources/application.properties.example src/main/resources/application.properties
    - sed -i "s/{DB_HOST}/$DB_HOST/g" src/main/resources/application.properties
    - sed -i "s/{DB_PORT}/$DB_PORT/g" src/main/resources/application.properties
    - sed -i "s/{DB_NAME}/$DB_NAME/g" src/main/resources/application.properties
    - sed -i "s/{DB_USER}/$DB_USER/g" src/main/resources/application.properties
    - sed -i "s/{DB_PASS}/$DB_PASS/g" src/main/resources/application.properties
    - sed -i "s/{JWT_KEY}/$JWT_KEY/g" src/main/resources/application.properties
    - dpl --provider=heroku --app=$HEROKU_APPNAME --api-key=$HEROKU_APIKEY --skip-cleanup
  environment:
    name: production
    url: $HEROKU_APP_HOST
  only:
    - master
